ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS razao_social text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS perfil_cliente text NOT NULL DEFAULT 'brasileiro',
  ADD COLUMN IF NOT EXISTS endereco text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cidade text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS logistica_principal text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS nome_proprietario text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cpf_responsavel text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cs_responsavel text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS manager text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS auxiliar text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS assistente text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS consultor_atual text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS vendedor text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status_financeiro text NOT NULL DEFAULT 'em_dia',
  ADD COLUMN IF NOT EXISTS multa_rescisoria numeric DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS data_fim_prevista date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fase_macro text NOT NULL DEFAULT 'implementacao',
  ADD COLUMN IF NOT EXISTS sub_status text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ultimo_contato date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ultima_resposta_cliente date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS motivo_atraso_geral text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS risco_churn text NOT NULL DEFAULT 'baixo',
  ADD COLUMN IF NOT EXISTS tipo_cliente text NOT NULL DEFAULT 'seller',
  ADD COLUMN IF NOT EXISTS data_prevista_passagem date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS data_real_passagem date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS prioridade_geral text NOT NULL DEFAULT 'P2',
  ADD COLUMN IF NOT EXISTS nps_ultimo numeric DEFAULT NULL;